### ISSUE TITLE
Running pophttp as systemd service

### ISSUE THREAD

**Issue by MickiCH** [brokeh/pophttp#7]
Great tool and I wanted to make it run as systemd service, but run into some problems regarding the config.ini.

I followed some general 

`[Unit]
Description=Pophttp service

[Service]
Type=simple
ExecStart=/usr/bin/python /opt/pophttp/pophttp.py

[Install]
WantedBy=multi-user.target`

The problem is that when I run it with this it seems not to take my config.ini into account. It is like it did no execute it in the right path.

I continued investigating and it looks like I get the same behaviour when running it manually.

----
Running it within the folder with:

`cd /opt/pophttp/
python pophttp.py -vv`

is returning:

Server started on on 0.0.0.0
2020-10-08 20:36:25,615 192.168.1.229 resp 200 in 312ms http://192.168.1.124/toggle

-> Works fine.

-----
On the other hand running from another folder:

`/usr/bin/python /opt/pophttp/pophttp.py `

is returning: 

Server started on on 0.0.0.0
2020-10-08 20:39:02,834 192.168.1.229 request 3495h,37659s,33542b,3612k,on not mapped to a URL

-> It looks like if it is not taking the config into account. (it was the exact same button).

Any idea on this? My only goal is to run the service as systemd and thats why I was using the absolute path.

Thank you

**Comment by Andrew-Brock** [comment]
I'm pretty sure I've figured out what the issue is with the double send and I'm working on a fix for it. I'm guessing that the 2 bridges are interfering with each other and resetting the internal state. I should be able to get a fix for this in the next day or 2.

As for the config, the default is `config.ini` in the current working directory. Either of the below in your service config should fix the issue
```ini
ExecStart=/usr/bin/python /opt/pophttp/pophttp.py --config /opt/pophttp/config.ini
```
or
```ini
WorkingDirectory=/opt/pophttp/
ExecStart=/usr/bin/python /opt/pophttp/pophttp.py
```

**Comment by MickiCH** [comment]
Perfect! Thank you very much it works great as a systemd service now.
